services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - apartment_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: ${IMAGE_NAME}
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - apartment_network
    restart: "no"
    command: ["./main", "--setup=true"]

  app:
    image: ${IMAGE_NAME}
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - apartment_network
    command: ["./main"]

networks:
  apartment_network:

volumes:
  db_data: