name: CD - Build & Deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: read
      packages: write

    outputs:
      image: ${{ steps.image.outputs.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        id: image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}:latest
            ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create .env
        run: |
          cat <<EOF > .env
          PORT=8080
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          DB_HOST=db
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PORT=5432
          POSTGRES_USER=${{ secrets.DB_USER }}
          POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
          POSTGRES_DB=${{ secrets.DB_NAME }}
          IMAGE_NAME=ghcr.io/${{ needs.build.outputs.image }}:latest
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}
          EOF

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key
          chmod 600 key
          echo "SSH key set up"
          cat key
          ls -la
      
      - name: Upload .env to server
        run: |
          scp -i key -o StrictHostKeyChecking=no .env \
          ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/home/ubuntu/apartment-ooad/app/.env

      - name: Upload docker-compose.prod.yml
        run: |
          scp -i key -o StrictHostKeyChecking=no \
            docker-compose.prod.yml \
            ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/home/ubuntu/apartment-ooad/app/docker-compose.prod.yml

      - name: Deploy
        run: |
          IMAGE=$(echo "${{ needs.build.outputs.image }}" | tr '[:upper:]' '[:lower:]')

          ssh -i key -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << EOF
            set -e
            ls
            cd apartment-ooad/app/

            echo "this is image bro !!!! $IMAGE"
            echo "📦 Pulling latest image..."
            docker pull ghcr.io/$IMAGE:latest

            echo "🔄 Restarting app..."
            echo "🧱 Running migrations..."
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans

            echo "🧹 Cleaning old images..."
            docker image prune -f

            echo "🧹 Cleaning unused Docker resources..."
            docker system prune -f

            echo "✅ Done"
          EOF

      - name: Cleanup SSH key
        if: always()
        run: rm -f key